# Generated by Django 5.2.6 on 2025-09-17 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.company'),
        ),
        migrations.AddField(
            model_name='application',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'opportunity')},
        ),
    ]
